frenck/action-addon-linter

README.md, src/build.schema.json, src/build.schema.ts, src/lint.py
This PR adds support for linting the `build.json` file if it exists. It also adds the schema that belongs to it.
Additionally, some checks for the community add-ons are added, e.g., to ensure the architectures in the build.json match the architectures listed in the config.json file.
=> Add support for linting build.json

.github/workflows/lint.yaml
So checks can be enabled actually... as emoji turns out to be hard for GitHub
=> Update linter workflow

src/config.schema.json, src/config.schema.ts
Adds new schema changes from Supervisor 2021.01.0.
- `boot` is now optional, and has a default value of `auto`.
- `options` is now optional
- `schema` is now optional
- `startup` is now optional, and has a default value of `application`
=> Add new optional/default from Supervisor 2021.01.0 release

src/config.schema.json, src/config.schema.ts
Fixes an issue where the map wasn't validated correctly.
This wasn't considered valid for the mapping configuration:
```json
{
"map": ["ssl:rw"]
}
```
=> Fix add-on config map check regular expression

src/config.schema.json, src/config.schema.ts
Fixes an issue with the port descriptions in the add-on configuration; expecting an integer. Of course, the description should have been a string.
=> Fix port description type

src/lint.py
Fixes an issue where the exit code was reset when a build.json is processed.
This causes the action to succeed successfully in case the config.json has errors, but build.json does not.
It now exists properly again.
=> Fix exit code reset

src/config.schema.json
The port number did not generate well from the original schema generator.
This corrects the JSON schema to handle the port numbers correctly.
=> Fix port number schema's

src/config.schema.json
Fixes an issue in the configuration schema, where the Home Assistant minimal version expected a boolean. This of course should be a string.
```json
{
"homeassistant": "2021.1"
}
```
=> Fix 'homeassistant' property to be of type string

src/config.schema.json
`privileged` can be an array of options.
=> Fix format of the 'privileged' option

.github/workflows/lint.yaml
The GitHub Actions linter workflow broke in this repository, due to a typo. Didn't cause any problems before, apparently, GitHub improved 🤷
=> Fix CI workflow

src/lint.py
In case Ingress is enabled with an add-on, the WEBUI button will always open via Ingress.
This makes setting `webui` in the add-on configuration at that point, unneeded.
This PR adds an additional check for this.
=> Check if 'webui' is abset when Ingress is enabled

src/lint.py
Adds additional checks around `ports` and `ports_description`.
- Ensures `ports_description` is there, when `ports` are defined.
- Ensures the ports listed in `ports` & `ports_description` match.
=> Add checks if ports & ports_description match

src/lint.py
This PR adds additional checks for when the add-on has enabled Ingress.
- When the add-on is running on the host network. The `ingress_port` should be 0.
- When the add-on is NOT running on the host network. The `ingress_port` should not be 0.
=> Add ingress_port checks

src/config.schema.json, src/lint.py
Adds support for the latest schema changes in the Supervisor.
- `auto_uart` is deprecated.
- `uart` is a new option.
- `tmpfs` is now a boolean.
- `devices` now expects a list of paths.
=> Adjust schema to match Supervisor 2021.2 new features

src/lint.py
Adds additional checks when using the `full_access` add-on option.
- Warn if used at all.
- Error if used together with `devices`, `gpio`, `usb` or `uart`.
See: https://github.com/home-assistant/developers.home-assistant/pull/812
=> Add checks and warnings for use of full_access

src/lint.py, src/requirements.txt
repository/config/build can now be .yml and .yaml in addition to .json
This PR adds checking for the new filetypes for config and build.
Closes #35 which I did not see until after creating this PR :see_no_evil:
=> Add support for YAML config/build files

src/config.schema.json
Adds new add-on option (ingress_stream) that is used to stream POST requests to the add-on over ingress
Ref:
<https://github.com/home-assistant/supervisor/pull/2982>
<https://github.com/home-assistant/developers.home-assistant/pull/989>
=> Add ingress_stream

src/config.schema.json, src/lint.py
This PR adds support for some newer options that were still missing in the validator:
- `snapshot`
- `snapshot_pre`
- `snapshot_post`
Additionally, it will check that pre/post is not used when a cold snapshot is configured.
=> Add support for new snapshot options

src/config.schema.json, src/lint.py
This PR prepares for the snapshot -> backup migration by already allowing the new backup version to be used.
See: <https://github.com/home-assistant/supervisor/pull/2940>
Once the change has been pushed upstream, we need to add extra checks/warnings.
=> Prepare snapshot -> backup migration

src/lint.py
This PR adds configuration validation errors for the snapshot -> backup change/migration.
The following options have been renamed:
- `snapshot` -> `backup`
- `snapshot_exclude` -> `backup_exclude`
- `snapshot_pre` -> `backup_pre`
- `snapshot_post` -> `backup_post`
🕐 Awaits release of: <https://github.com/home-assistant/supervisor/pull/2940>
=> Deprecate snapshot options, use backup instead

src/config.schema.json, src/lint.py
This PR removes the snapshot deprecation warnings.
The linter will now error on the use of the old `snapshot*` configuration parameters
=> Remove snapshot deprecation warnings

src/config.schema.json
Add support for setting the codenotary signers emails address in the add-on configuration
https://github.com/home-assistant/supervisor/pull/3450
=> Add codenotary support to add-on configuration

src/lint.py
This change is for preparing for single image multi arch deployments for add-ons.
The linter currently checks if `build_from` in the build.yaml file matches the archs listed in config.yaml.
This PR adds a little slack to that, to skip this check if `build_from` is missing in build.yaml completely.
=> Allow build.json without build_from

src/lint.py
When in community add-ons mode, we require the arch & build_from to match in architectures. When using a multiarch manifest image in the build configuration, that rule shouldn't apply.
=> Only require build_from and arch to match when not using image manifest

src/lint.py
This PR removes a linting check/rule that ensured if `ingress_port` was set to `0` when the addon ran on the host network.
That rule is actually incorrect. In case an application supports ingress directly, no proxy is needed, and thus the application port can be used directly.
=> Remove incorrect ingress port on host network rule

src/lint.py
Detect and error on the use of the `watchdog` configuration option. It became fully obsolete now the Supervisor supports the native Docker HEALTHCHECK directive natively.
There are so many advantages to using the HEALTHCHECK (in terms of features, being event driven and much more), that is makes absolutely no sense to use the older `watchdog` feature.
=> Detect use of obsolete watchdog configuration option

src/config.schema.json, src/lint.py
Ref: <https://developers.home-assistant.io/blog/2023/11/06/public-addon-config>
=> Add linting against new mapping changes

src/lint.py
This PR adds additional linter checks to offending settings in the mapping options.
`homeassistant_config` and `config` conflict. They both have the same goal, but one is the latter is the older deprecated version.
`addon_config` conflicts with `config`, as those share the same mount destination (`/config`).
=> Add checks for conflicting mapping options

src/config.schema.json
Extension of the add-on config check with the recently added `breaking_versions` option. Available since supervisor version [2024.01.1](https://github.com/home-assistant/supervisor/releases/tag/2024.01.1).
https://github.com/home-assistant/supervisor/pull/4832
https://github.com/home-assistant/developers.home-assistant/pull/2056
=> Adds breaking_versions config option check

src/config.schema.json
`host_uts`property is not defined in config.schema.json and the linter fails if it is added to a configuration:
```
Error: Additional properties are not allowed ('host_uts' was unexpected)
```
=> Add host_uts support
